name: 'test-pull-request'

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test lint
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔎 The name of your branch is ${{ github.ref }}"

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - run: npm run lint -- --max-warnings=0
